[FEATURE] Add display mode "time restriction"
derhansen/sf_event_mgt pull request #857
Opened 2021-02-21 13:44 UTC by christophlehmann

Relates: #482

This adds the display mode time restriction.

<img width="482" alt="feature-display-mode-time-restriction" src="https://user-images.githubusercontent.com/4953689/108626786-46450200-7452-11eb-8600-7c8bab126174.png">

2021-02-22 14:02 UTC, derhansen requested changes

2021-02-27 16:53 UTC, christophlehmann commented on Classes/Domain/Repository/EventRepository.php
> +                            $query->greaterThan('enddate', $timeRestriction),
Thanks for the review!

2021-03-02 07:24 UTC, derhansen approved these changes

2021-03-26 19:31 UTC, christophlehmann commented
I added flash messages for evaluation of time restriction values. Editors will have a better user experience, because `strtotime()` expressions may be misunderstood regarding begin and end of a day. 

<img width="600" alt="timerestriction-flashmessages" src="https://user-images.githubusercontent.com/4953689/112683291-9cea9500-8e71-11eb-91a6-cd94c120f446.png">

2021-03-28 11:18 UTC, derhansen commented
👍  Yes, really good to have  user friendly notification for the new time restriction.

2021-04-04 12:38 UTC, merged